ssh:
  host: ${SSH_HOST:192.168.50.61}
  port: ${SSH_PORT:22}
  username: ${SSH_USERNAME:root}
  password: ${SSH_PASSWORD:123456}
  connect-timeout: ${CONNECT_TIMEOUT:5000}

spring:
  thymeleaf:
    cache: false
    mode: HTML

server:
  port: 8123